settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: main.go
  path: server/main.go
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
