version: 2
jobs:
  test-routine:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/tamuhack-org/quack
    environment:
      - DEP_VERSION: 0.4.1
    steps:
      - checkout
workflows:
  version: 2
  test_and_build:
    jobs:
      - test-routine

