version: 2
jobs:
  test-routine:
    docker:
      - image: circleci/golang:1.10.0
    working_directory: /go/src/github.com/tamuhack-org/quack
    environment:
      - DEP_VERSION: 0.4.1
    steps:
      - checkout
      - run: go get github.com/gorilla/handlers
      - run: go get github.com/gorilla/mux
      - run: go get github.com/globalsign/mgo
      - run:
          name: test
          command: |
              go build -v
              go test -p 6 -race ./...
      - setup_remote_docker
      - run: docker build --rm=false -t gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
  build-deploy-routine:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: ls
      - run: echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
      - run: gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
      - run: gcloud --quiet config set project ${GCP_PROJECT}
      - run: gcloud config set compute/zone ${CLOUDSDK_COMPUTE_ZONE}
      - run: gcloud --quiet container clusters get-credentials $CLUSTER_NAME
      - setup_remote_docker
      - run: ls
      - run: docker build --rm=false -t gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1 .
      - run: gcloud docker -- push gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1
      - run: kubectl set image deployment/tamuhack-quack tamuhack-quack=gcr.io/${GCP_PROJECT}/${IMAGE_NAME}:$CIRCLE_SHA1
workflows:
  version: 2
  test_and_build:
    jobs:
      - build-deploy-routine:
          filters:
            branches:
              only: master
      - test-routine


